version: "3.9"

services:
  groove-records:
    image: groove-records
    container_name: groove-records-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: grooverecords
      MYSQL_USER: emanuel
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3307:3306"
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql


networks:
  spring-network:
volumes:
  mysql-volume:
